/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Panel;

import Mylib.LookAndFeelWindow;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author SVE1521BCX
 */
public class pnLogin extends javax.swing.JDialog {
    private boolean exit, check;
    private Connection con;
    private int count = 0, id_manager;
    private String username, password, tendangnhap;
    
    public boolean getCheck() {
        return check;
    }

    public void setCheck(boolean check) {
        this.check = check;
    }

    public boolean isExit() {
        return exit;
    }

    public void setExit(boolean exit) {
        this.exit = exit;
    }
    
    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public int getId_manager() {
        return id_manager;
    }

    public void setId_manager(int id_manager) {
        this.id_manager = id_manager;
    }

    public String getTendangnhap() {
        return tendangnhap;
    }

    public void setTendangnhap(String tendangnhap) {
        this.tendangnhap = tendangnhap;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }
    
    public pnLogin(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    private boolean connect(){
        try{
            LookAndFeelWindow.LookAndFeelWindow();
            Statement stManager = con.createStatement();
            password = new String(txtPassword.getPassword());
            password = password.trim();
            username = txtUsername.getText().trim();
            Pattern pUser = Pattern.compile("[a-zA-Z\\d]{3,15}");
            Matcher mUser = pUser.matcher(username);
            
            if (mUser.matches() == false) {
                check = false;
            }
            if (password.trim().length() > 15 || password.trim().length() < 3) {
                check = false;
            }
            
            ResultSet rsManager = stManager.executeQuery("select * from Manager where TenDangNhap = '" + username + "' And MatKhau = '" + password + "'");
            if (rsManager.next()) {
                tendangnhap = rsManager.getString(2);
                id_manager = rsManager.getInt(1);
                check = true;
            }
            if (rsManager.wasNull()) {
                check = false;
            }
            rsManager.close();
            stManager.close();
        }catch(Exception ex){
            ex.printStackTrace();
        }
        return check;
        
    }
    public pnLogin(java.awt.Frame parent, final Connection con) {
        super(parent, "Login", true);
        this.con = con;
        initComponents();
        txtUsername.requestFocusInWindow();
        addWindowListener(new java.awt.event.WindowAdapter() {

            public void windowClosing(java.awt.event.WindowEvent e) {
                try {
                    con.close();
                } catch (SQLException ex) {
                    Logger.getLogger(pnLogin.class.getName()).log(Level.SEVERE, null, ex);
                }
                System.exit(0);
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        btLogin = new javax.swing.JButton();
        btExit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setMaximumSize(new java.awt.Dimension(500, 400));
        jPanel1.setMinimumSize(new java.awt.Dimension(500, 400));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 400));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 51));
        jLabel1.setText("ATM LOGIN MANAGER");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(130, 100, 239, 26);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel3.setText("Username:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(80, 170, 84, 19);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel4.setText("Password:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(80, 220, 83, 19);
        jPanel1.add(txtUsername);
        txtUsername.setBounds(180, 162, 220, 30);

        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPasswordKeyPressed(evt);
            }
        });
        jPanel1.add(txtPassword);
        txtPassword.setBounds(180, 212, 220, 30);

        btLogin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Download-icon.png"))); // NOI18N
        btLogin.setText("Login");
        btLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btLogin);
        btLogin.setBounds(160, 270, 97, 41);

        btExit.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Stop-icon.png"))); // NOI18N
        btExit.setText("Exit");
        btExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExitActionPerformed(evt);
            }
        });
        jPanel1.add(btExit);
        btExit.setBounds(280, 270, 89, 41);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/login_background_1.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 500, 400);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyPressed
        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {
            connect();
            if (check == false) {
                count++;
                JOptionPane.showMessageDialog(null, "Username or Password is invalid, please try again !!!\nYou have " + (3 - count) + " times to try.");
                txtUsername.requestFocusInWindow();
                txtPassword.setText(null);
            } else {
                dispose();
            }
            if (count == 3) {
                System.exit(0);
            }

        }
    }//GEN-LAST:event_txtPasswordKeyPressed

    private void btLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLoginActionPerformed
        connect();
        if(txtUsername.getText().trim().length() == 0 || new String(txtPassword.getPassword()).trim().length() == 0){
            JOptionPane.showMessageDialog(null, "Please enter username or password");
        }else{
        if (check == false) {
            count++;
            JOptionPane.showMessageDialog(null, "Username or Password is invalid, please try again !!!\nYou have " + (3 - count) + " times to try.");
            txtUsername.requestFocusInWindow();
            txtPassword.setText(null);
        } else {
            dispose();
        }
        if (count == 3) {
            System.exit(0);
        }
        }
    }//GEN-LAST:event_btLoginActionPerformed

    private void btExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExitActionPerformed
        exit = true;
        dispose();
    }//GEN-LAST:event_btExitActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btExit;
    private javax.swing.JButton btLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
