/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panel;

import MyProject.Run;
import TBClass.tbAccount;
import java.awt.event.KeyEvent;
import java.util.Locale;
import java.util.ResourceBundle;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Phong
 */
public class pnChangePin extends javax.swing.JPanel {

    Run run;
    boolean lang;
    Locale loc;
    ResourceBundle rs;
    DefaultTableModel model;
    int atm, card, count = 0;
    tbAccount cus = new tbAccount();

    public pnChangePin(Run run, boolean lang, int atm, int card) {
        initComponents();
        this.run = run;
        this.lang = lang;
        this.atm = atm;
        this.card = card;

        if (lang) {
            loc = new Locale("vi", "VN");
        } else {
            loc = new Locale("en", "EN");
        }
        rs = ResourceBundle.getBundle("Lang.td", loc);
        lbPin_0.setText(rs.getString("lbPin_0"));
        lbPin_1.setText(rs.getString("lbPin_1"));
        lbPin_2.setText(rs.getString("lbPin_2"));
        lbPin_3.setText(rs.getString("lbPin_3"));
    }

    public pnChangePin() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbPin_0 = new javax.swing.JLabel();
        lbPin_1 = new javax.swing.JLabel();
        lbPin_2 = new javax.swing.JLabel();
        lbPin_3 = new javax.swing.JLabel();
        txtOPin = new javax.swing.JPasswordField();
        txtNPin = new javax.swing.JPasswordField();
        txtRPin = new javax.swing.JPasswordField();
        btnOk = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(931, 626));
        setMinimumSize(new java.awt.Dimension(931, 626));
        setPreferredSize(new java.awt.Dimension(931, 626));
        setLayout(null);

        lbPin_0.setFont(new java.awt.Font("Tahoma", 0, 27)); // NOI18N
        lbPin_0.setText("ĐỔI MÃ PIN");
        add(lbPin_0);
        lbPin_0.setBounds(370, 80, 340, 62);

        lbPin_1.setFont(new java.awt.Font("Tahoma", 0, 27)); // NOI18N
        lbPin_1.setText("MÃ PIN CŨ");
        add(lbPin_1);
        lbPin_1.setBounds(246, 166, 205, 33);

        lbPin_2.setFont(new java.awt.Font("Tahoma", 0, 27)); // NOI18N
        lbPin_2.setText("MÃ PIN MỚI");
        add(lbPin_2);
        lbPin_2.setBounds(246, 234, 338, 33);

        lbPin_3.setFont(new java.awt.Font("Tahoma", 0, 27)); // NOI18N
        lbPin_3.setText("NHẬP LẠI MÃ PIN");
        add(lbPin_3);
        lbPin_3.setBounds(246, 303, 338, 33);

        txtOPin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOPinActionPerformed(evt);
            }
        });
        add(txtOPin);
        txtOPin.setBounds(520, 170, 157, 34);
        add(txtNPin);
        txtNPin.setBounds(520, 240, 157, 33);
        add(txtRPin);
        txtRPin.setBounds(520, 310, 157, 33);

        btnOk.setFont(new java.awt.Font("Tahoma", 0, 27)); // NOI18N
        btnOk.setText("OK");
        btnOk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOkMouseClicked(evt);
            }
        });
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });
        add(btnOk);
        btnOk.setBounds(310, 370, 147, 41);

        btnHome.setText("HOME");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        add(btnHome);
        btnHome.setBounds(500, 370, 147, 41);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BannerTran.jpg"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 931, 626);
    }// </editor-fold>//GEN-END:initComponents

    private void txtOPinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOPinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOPinActionPerformed

    private void btnOkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOkMouseClicked
        String pin = new String(txtOPin.getPassword());
        Integer pinN = Integer.parseInt(String.valueOf(txtNPin.getPassword()));
        String pinNN = String.valueOf(txtNPin.getPassword());
        String pinR = String.valueOf(txtRPin.getPassword());
        
        String txtPin = lbPin_1.getText();
        String txtOP = lbPin_2.getText();
        String txtRP = lbPin_3.getText();
        
        Pattern p = Pattern.compile("^[0-9]{4}$");
        Matcher m = p.matcher(pin);
        if(pin.equals("")){
            JOptionPane.showMessageDialog(this, rs.getString("pin_null"));
        }
        else if(pinN.equals(""))
        {
            JOptionPane.showMessageDialog(this, rs.getString("pinN_null"));
        }
        else if (!pinNN.equals(pinR)) {
            JOptionPane.showMessageDialog(this, rs.getString("pin_retype"));
        } else {
            if (!m.matches()) {
                JOptionPane.showMessageDialog(this, rs.getString("pin_pattern_err"));
            } else if (!cus.checkPin(card, Integer.parseInt(pin))) {
                JOptionPane.showMessageDialog(this, rs.getString("pin_match_err"));
            } else {
                tbAccount.UpdatePin(card, pinN);
            }
        }
    }//GEN-LAST:event_btnOkMouseClicked

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOkActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        run.pnMain.removeAll();
        run.pnMain.add(new pnMain(run, lang, atm, card));
        run.pnMain.revalidate();
    }//GEN-LAST:event_btnHomeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbPin_0;
    private javax.swing.JLabel lbPin_1;
    private javax.swing.JLabel lbPin_2;
    private javax.swing.JLabel lbPin_3;
    private javax.swing.JPasswordField txtNPin;
    private javax.swing.JPasswordField txtOPin;
    private javax.swing.JPasswordField txtRPin;
    // End of variables declaration//GEN-END:variables
}
